[package]
edition = "2021"
name = "swc_plugin_remove_es_module_mark"
version = "0.1.0"

[dependencies]
swc_core = { workspace = true, features = [
  "common",
  "ecma_ast",
  "ecma_visit",
  "ecma_quote",
] }
modern_swc_plugins_utils = { path = "../swc_plugins_utils" }
serde = { workspace = true }
